version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/go:1.16'
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: go build
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1..1.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
